# Generated by Django 6.0.4 on 2026-04-24 17:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterfazDeComunicacion',
            fields=[
                ('Id_Interfaz', models.AutoField(primary_key=True, serialize=False)),
                ('tipos_puerto', models.CharField(blank=True, max_length=200, verbose_name='Tipos de Puerto')),
                ('Fecha_Reg', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Interfaz de Comunicación',
                'verbose_name_plural': 'Interfaces de Comunicación',
                'ordering': ['Id_Interfaz'],
            },
        ),
        migrations.CreateModel(
            name='NivelTension',
            fields=[
                ('Id_Ten', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo_ten', models.CharField(max_length=50)),
                ('Nivel', models.CharField(max_length=50)),
                ('Fecha_Reg', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nivel de Tensión',
                'verbose_name_plural': 'Niveles de Tensión',
                'ordering': ['Id_Ten'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('Id_user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('Nombre', models.CharField(max_length=100)),
                ('Correo', models.EmailField(max_length=254)),
                ('Nivel_User', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'ordering': ['Id_user'],
            },
        ),
        migrations.CreateModel(
            name='PuertoComunicacion',
            fields=[
                ('Id_Puerto', models.AutoField(primary_key=True, serialize=False)),
                ('Numero_Puerto', models.CharField(max_length=50, verbose_name='Número de Puerto')),
                ('Descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Mantenimiento', 'Mantenimiento')], default='Activo', max_length=50, verbose_name='Estado')),
                ('Observaciones', models.TextField(blank=True, verbose_name='Observaciones')),
                ('Fecha_Reg', models.DateField(auto_now_add=True)),
                ('Id_Interfaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puertos', to='equipos.interfazdecomunicacion')),
            ],
            options={
                'verbose_name': 'Puerto de Comunicación',
                'verbose_name_plural': 'Puertos de Comunicación',
                'ordering': ['Id_Puerto'],
            },
        ),
        migrations.CreateModel(
            name='Subestacion',
            fields=[
                ('Id_Sub_est', models.AutoField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=100)),
                ('Ubicación', models.CharField(max_length=200)),
                ('Estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Mantenimiento', 'Mantenimiento')], default='Activo', max_length=50)),
                ('Fecha_Reg', models.DateField(auto_now_add=True)),
                ('Id_Ten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subestaciones', to='equipos.niveltension')),
            ],
            options={
                'verbose_name': 'Subestación',
                'verbose_name_plural': 'Subestaciones',
                'ordering': ['Id_Sub_est'],
            },
        ),
        migrations.CreateModel(
            name='Rele',
            fields=[
                ('Id_relé', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=50)),
                ('Observaciones', models.TextField(blank=True)),
                ('Fecha_Reg', models.DateField(auto_now_add=True)),
                ('Id_Ten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reles', to='equipos.niveltension')),
                ('Id_Sub_est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reles', to='equipos.subestacion')),
            ],
            options={
                'verbose_name': 'Relé',
                'verbose_name_plural': 'Relés',
                'ordering': ['Id_relé'],
            },
        ),
    ]
