# Generated by Django 6.0.4 on 2026-04-24 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interfazdecomunicacion',
            name='tipos_puerto',
        ),
        migrations.RemoveField(
            model_name='puertocomunicacion',
            name='Descripcion',
        ),
        migrations.RemoveField(
            model_name='puertocomunicacion',
            name='Numero_Puerto',
        ),
        migrations.RemoveField(
            model_name='puertocomunicacion',
            name='Observaciones',
        ),
        migrations.AddField(
            model_name='interfazdecomunicacion',
            name='Puertos_C',
            field=models.IntegerField(default=0, verbose_name='Puertos de Comunicación'),
        ),
        migrations.AddField(
            model_name='puertocomunicacion',
            name='Tipo',
            field=models.CharField(choices=[('ETH', 'Ethernet'), ('RS232', 'RS232'), ('RS485', 'RS485'), ('USB', 'USB'), ('FIBRA', 'Fibra Óptica')], default='ETH', max_length=10, verbose_name='Tipo de Puerto'),
        ),
        migrations.AlterField(
            model_name='puertocomunicacion',
            name='Estado',
            field=models.CharField(default='Activo', max_length=50, verbose_name='Estado'),
        ),
    ]
