# Generated by Django 6.0.4 on 2026-04-27 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_remove_interfazdecomunicacion_tipos_puerto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protocolo',
            fields=[
                ('Id_Protocolo', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(choices=[('104', 'IEC 104'), ('DNP', 'DNP3'), ('GOOSE', 'GOOSE'), ('101', 'IEC 101'), ('MODBUS', 'Modbus')], max_length=10, verbose_name='Tipo de Protocolo')),
                ('Estado', models.CharField(default='Activo', max_length=50, verbose_name='Estado')),
                ('Fecha_Reg', models.DateField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('Id_Interfaz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolos', to='equipos.interfazdecomunicacion', verbose_name='Interfaz')),
            ],
            options={
                'verbose_name': 'Protocolo de Comunicación',
                'verbose_name_plural': 'Protocolos de Comunicación',
                'ordering': ['Id_Protocolo'],
            },
        ),
    ]
