# Generated by Django 6.0.4 on 2026-04-27 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_protocolo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolo',
            name='Id_Interfaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos', to='equipos.interfazdecomunicacion', verbose_name='Interfaz'),
        ),
    ]
