# Generated by Django 6.0.4 on 2026-04-27 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0005_alter_protocolo_id_interfaz'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subestacion',
            name='Estado',
        ),
    ]
