# Generated by Django 6.0.4 on 2026-04-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_remove_subestacion_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='rele',
            name='Protocolos',
            field=models.ManyToManyField(blank=True, related_name='reles_asociados', to='equipos.protocolo'),
        ),
        migrations.AddField(
            model_name='rele',
            name='Puertos',
            field=models.ManyToManyField(blank=True, related_name='reles_asociados', to='equipos.puertocomunicacion'),
        ),
    ]
