# Generated by Django 6.0.4 on 2026-04-29 15:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0007_rele_protocolos_rele_puertos'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='interfazdecomunicacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interfaces_creadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='niveltension',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='niveles_tension_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='puertocomunicacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puertos_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rele',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reles_creados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subestacion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subestaciones_creadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
