# Generated by Django 6.0.4 on 2026-05-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_interfazdecomunicacion_creado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subestacion',
            name='Coordenadas',
            field=models.CharField(blank=True, max_length=100, verbose_name='Coordenadas'),
        ),
    ]
