# Generated by Django 6.0.4 on 2026-05-05 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0009_subestacion_coordenadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='rele',
            name='Imagen',
            field=models.ImageField(blank=True, null=True, upload_to='reles/', verbose_name='Imagen del relé'),
        ),
    ]
