# Generated by Django 6.0.4 on 2026-05-05 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0010_rele_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rele',
            name='EsRemoto',
            field=models.BooleanField(default=False, verbose_name='¿Posee Remota?'),
        ),
        migrations.AddField(
            model_name='rele',
            name='Remota_Id_Ten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reles_remotos', to='equipos.niveltension', verbose_name='Nivel de tensión de la remota'),
        ),
        migrations.AddField(
            model_name='rele',
            name='Remota_Marca',
            field=models.CharField(blank=True, max_length=100, verbose_name='Marca de la remota'),
        ),
        migrations.AddField(
            model_name='rele',
            name='Remota_Modelo',
            field=models.CharField(blank=True, max_length=100, verbose_name='Modelo de la remota'),
        ),
    ]
