# Generated by Django 6.0.4 on 2026-05-05 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0011_rele_esremoto_rele_remota_id_ten_rele_remota_marca_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveltension',
            name='Nivel',
            field=models.CharField(choices=[('230kV', '230 kV'), ('115kV', '115 kV'), ('34.5kV', '34.5 kV'), ('13.8kV', '13.8 kV'), ('4.16kV', '4.16 kV'), ('0.48kV', '0.48 kV')], max_length=10),
        ),
        migrations.AlterField(
            model_name='niveltension',
            name='Tipo_ten',
            field=models.CharField(choices=[('AT', 'Alta Tensión'), ('MT', 'Media Tensión'), ('BT', 'Baja Tensión')], default='AT', max_length=5),
        ),
    ]
