# Generated by Django 6.0.4 on 2026-05-05 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0012_alter_niveltension_nivel_alter_niveltension_tipo_ten'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveltension',
            name='Nivel',
            field=models.CharField(choices=[('230kV', '230 kV'), ('115kV', '115 kV'), ('34.5kV', '34.5 kV'), ('13.8kV', '13.8 kV')], max_length=10),
        ),
    ]
