# Generated by Django 6.0.4 on 2026-05-06 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0013_alter_niveltension_nivel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Remota',
            fields=[
                ('Id_Remota', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Fecha_Reg', models.DateField(auto_now_add=True)),
                ('Id_Ten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remotas', to='equipos.niveltension')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remotas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Remota',
                'verbose_name_plural': 'Remotas',
                'ordering': ['Id_Remota'],
            },
        ),
    ]
