# Generated by Django 6.0.4 on 2026-05-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0014_remota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rele',
            name='Remota_Id_Ten',
        ),
        migrations.RemoveField(
            model_name='rele',
            name='Remota_Marca',
        ),
        migrations.RemoveField(
            model_name='rele',
            name='Remota_Modelo',
        ),
        migrations.AddField(
            model_name='rele',
            name='Remota',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reles_asociados', to='equipos.remota', verbose_name='Remota asociada'),
        ),
    ]
