# Generated by Django 6.0.4 on 2026-05-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0015_remove_rele_remota_id_ten_remove_rele_remota_marca_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='remota',
            name='Interfaces',
            field=models.ManyToManyField(blank=True, related_name='remotas_asociadas', to='equipos.interfazdecomunicacion'),
        ),
        migrations.AddField(
            model_name='remota',
            name='Niveles_Ten',
            field=models.ManyToManyField(blank=True, related_name='remotas_multiples', to='equipos.niveltension'),
        ),
        migrations.AddField(
            model_name='remota',
            name='Protocolos',
            field=models.ManyToManyField(blank=True, related_name='remotas_asociadas', to='equipos.protocolo'),
        ),
    ]
