# Generated by Django 6.0.4 on 2026-05-12 15:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0016_add_remota_relations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconectador',
            fields=[
                ('Id_reconectador', models.AutoField(primary_key=True, serialize=False)),
                ('Marca', models.CharField(max_length=100)),
                ('Modelo', models.CharField(max_length=100)),
                ('Estado', models.CharField(max_length=50)),
                ('Observaciones', models.TextField(blank=True)),
                ('Imagen', models.ImageField(blank=True, null=True, upload_to='reconectadores/', verbose_name='Imagen del reconectador')),
                ('Fecha_Reg', models.DateField(auto_now_add=True)),
                ('Id_Sub_est', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconectadores', to='equipos.subestacion')),
                ('Id_Ten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconectadores', to='equipos.niveltension')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconectadores_creados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reconectador',
                'verbose_name_plural': 'Reconectadores',
                'ordering': ['Id_reconectador'],
            },
        ),
    ]
