# Generated by Django 6.0.4 on 2026-05-13 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0017_reconectador'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interfazdecomunicacion',
            options={'ordering': ['Id_Interfaz'], 'verbose_name': 'Interfaz de Comunicación', 'verbose_name_plural': 'Interfaces de Comunicación'},
        ),
        migrations.AddField(
            model_name='interfazdecomunicacion',
            name='Tipo_Interfaz',
            field=models.CharField(choices=[('PUERTOS', 'Puertos de Comunicación'), ('PROTOCOLOS', 'Protocolos de Comunicación')], default='PUERTOS', max_length=20, verbose_name='Tipo de Interfaz'),
        ),
    ]
