# Generated by Django 6.0.4 on 2026-05-15 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0019_assign_tipo_interfaz'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfazdecomunicacion',
            name='Activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='Activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AlterField(
            model_name='interfazdecomunicacion',
            name='Puertos_C',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Puertos'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='Id_Interfaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='protocolos', to='equipos.interfazdecomunicacion', verbose_name='Interfaz'),
        ),
        migrations.AlterField(
            model_name='puertocomunicacion',
            name='Id_Interfaz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='puertos', to='equipos.interfazdecomunicacion'),
        ),
    ]
