# Generated by Django 6.0.4 on 2026-05-19 01:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0020_add_activo_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('Id_Evento', models.AutoField(primary_key=True, serialize=False)),
                ('Tipo', models.CharField(choices=[('CREACION', 'Creación'), ('ACTUALIZACION', 'Actualización'), ('ELIMINACION', 'Eliminación'), ('LOGIN', 'Inicio de Sesión'), ('LOGOUT', 'Cierre de Sesión'), ('ERROR', 'Error'), ('OTRO', 'Otro')], default='OTRO', max_length=20)),
                ('Descripcion', models.TextField()),
                ('Fecha_Hora', models.DateTimeField(auto_now_add=True)),
                ('IP_Address', models.GenericIPAddressField(blank=True, null=True)),
                ('Usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Bitácora de Eventos',
                'ordering': ['-Fecha_Hora'],
            },
        ),
    ]
