# Generated by Django 6.0.4 on 2026-05-19 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0021_evento'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-Fecha_Hora'], 'verbose_name': 'Evento', 'verbose_name_plural': 'Registro de Eventos'},
        ),
    ]
