# Generated by Django 5.2.14 on 2026-05-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0022_alter_evento_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='Vista',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
