# Generated by Django 6.0.4 on 2026-05-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0023_add_vista_to_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='permisos',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
