# Generated by Django 5.2.14 on 2026-05-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0024_add_permisos_to_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='rele',
            name='Puertos_IPs',
            field=models.JSONField(blank=True, default=dict, verbose_name='IPs por puerto ETH del relé'),
        ),
        migrations.AddField(
            model_name='rele',
            name='Remota_IPs',
            field=models.JSONField(blank=True, default=dict, verbose_name='IPs por puerto ETH de la remota'),
        ),
    ]
