# Generated by Django 5.2.14 on 2026-05-27 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0025_rele_puertos_ips_rele_remota_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='rele',
            name='Contadores',
            field=models.PositiveIntegerField(default=0, verbose_name='Contadores'),
        ),
        migrations.AddField(
            model_name='rele',
            name='Entradas_Analogicas',
            field=models.PositiveIntegerField(default=0, verbose_name='Entradas Analógicas'),
        ),
        migrations.AddField(
            model_name='rele',
            name='Entradas_Digitales',
            field=models.PositiveIntegerField(default=0, verbose_name='Entradas Digitales'),
        ),
        migrations.AddField(
            model_name='rele',
            name='Salidas_Digitales',
            field=models.PositiveIntegerField(default=0, verbose_name='Salidas Digitales'),
        ),
    ]
