# Generated by Django 5.2.14 on 2026-05-27 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0026_rele_contadores_rele_entradas_analogicas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remota',
            name='Id_Ten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remotas', to='equipos.niveltension'),
        ),
    ]
