# Generated by Django 5.2.14 on 2026-05-27 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0027_alter_remota_id_ten'),
    ]

    operations = [
        migrations.AddField(
            model_name='rele',
            name='Remota_Puertos',
            field=models.JSONField(blank=True, default=list, verbose_name='Puertos de la remota seleccionados (claves iface_puerto)'),
        ),
    ]
