# Generated by Django 5.2.14 on 2026-05-31 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0028_rele_remota_puertos'),
    ]

    operations = [
        migrations.AddField(
            model_name='subestacion',
            name='Niveles_Ten',
            field=models.ManyToManyField(blank=True, related_name='subestaciones_multiples', to='equipos.niveltension'),
        ),
        migrations.AlterField(
            model_name='subestacion',
            name='Id_Ten',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subestaciones', to='equipos.niveltension'),
        ),
    ]
