# Generated by Django 5.2.14 on 2026-05-31 16:14

from django.db import migrations


def backfill_niveles(apps, schema_editor):
    """Copia el Id_Ten existente de cada subestación al nuevo M2M Niveles_Ten."""
    Subestacion = apps.get_model('equipos', 'Subestacion')
    for sub in Subestacion.objects.exclude(Id_Ten__isnull=True):
        sub.Niveles_Ten.add(sub.Id_Ten_id)


def reverse_backfill(apps, schema_editor):
    Subestacion = apps.get_model('equipos', 'Subestacion')
    for sub in Subestacion.objects.all():
        sub.Niveles_Ten.clear()


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0029_subestacion_niveles_ten_alter_subestacion_id_ten'),
    ]

    operations = [
        migrations.RunPython(backfill_niveles, reverse_backfill),
    ]
