# Generated by Django 5.2.14 on 2026-05-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0030_backfill_subestacion_niveles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puertocomunicacion',
            name='Tipo',
            field=models.CharField(choices=[('ETH', 'Ethernet'), ('RS232', 'RS232'), ('RS485', 'RS485'), ('USB', 'USB'), ('FIBRA', 'Fibra Óptica')], default='ETH', max_length=30, verbose_name='Tipo de Puerto'),
        ),
    ]
