# Generated by Django 5.2.14 on 2026-05-31 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0031_alter_puertocomunicacion_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='puertocomunicacion',
            name='Descripcion',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Descripción'),
        ),
    ]
