# Generated by Django 5.2.14 on 2026-05-31 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0032_puertocomunicacion_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='puertocomunicacion',
            name='Icono',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Ícono'),
        ),
    ]
