# Generated by Django 5.2.14 on 2026-05-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0033_puertocomunicacion_icono'),
    ]

    operations = [
        migrations.AddField(
            model_name='protocolo',
            name='Descripcion',
            field=models.CharField(blank=True, default='', max_length=80, verbose_name='Descripción'),
        ),
        migrations.AddField(
            model_name='protocolo',
            name='Icono',
            field=models.CharField(blank=True, default='', max_length=40, verbose_name='Ícono'),
        ),
        migrations.AlterField(
            model_name='protocolo',
            name='Tipo',
            field=models.CharField(choices=[('104', 'IEC 104'), ('DNP', 'DNP3'), ('GOOSE', 'GOOSE'), ('101', 'IEC 101'), ('MODBUS', 'Modbus')], max_length=30, verbose_name='Tipo de Protocolo'),
        ),
    ]
