# Generated by Django 5.2.14 on 2026-06-01 17:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0035_tipopuertopersonalizado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProtocoloPersonalizado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=30, unique=True, verbose_name='Tipo')),
                ('Descripcion', models.CharField(blank=True, default='', max_length=80, verbose_name='Descripción')),
                ('Icono', models.CharField(blank=True, default='', max_length=40, verbose_name='Ícono')),
                ('Activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('Fecha_Reg', models.DateField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tipos_protocolo_personalizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tipo de Protocolo Personalizado',
                'verbose_name_plural': 'Tipos de Protocolo Personalizados',
                'ordering': ['Tipo'],
            },
        ),
    ]
