# Generated by Django 5.2.14 on 2026-06-11 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0036_tipoprotocolopersonalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rele',
            name='Puertos',
        ),
        migrations.RemoveField(
            model_name='reconectador',
            name='Id_Sub_est',
        ),
        migrations.RemoveField(
            model_name='reconectador',
            name='Id_Ten',
        ),
        migrations.RemoveField(
            model_name='reconectador',
            name='creado_por',
        ),
        migrations.DeleteModel(
            name='PuertoComunicacion',
        ),
        migrations.DeleteModel(
            name='Reconectador',
        ),
    ]
