# Generated by Django 5.2.14 on 2026-06-14 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0038_interfazdc_tipo_puerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rele',
            name='Remota_Puertos',
            field=models.JSONField(blank=True, default=list, verbose_name='Puertos de la remota seleccionados'),
        ),
    ]
