# Generated by Django 5.2.14 on 2026-06-14 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0039_alter_rele_remota_puertos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protocolo',
            name='Estado',
        ),
    ]
